
void edytor(UsePlik &mapki,short int num)
{
	BITMAP *mapa_tym;
	mapa_tym=load_bmp("mp_szab.bmp",0);
	mapa=create_bitmap(800,600);
	clear_to_color(mapa,makecol(255,0,255));
	draw_sprite(mapa,mapa_tym,0,0);
	LoadMap(mapki,num);
	rysuj(0);
	draw_sprite(mapa,pionek,startx*50+50,starty*50+50);
	bool nacis=true;
	x=0;
	y=0;
	short int oststartpozx=0,oststartpozy=0,ostcelpozx=13,ostcelpozy=9;
	while(!key[KEY_ESC])
	{
		if(key[KEY_LEFT])
		{
			if(!nacis)
			{
				x--;
				if(x<0)
				x=wieltab[0]-1;
				nacis=true;
			}
		}
		else
		if(key[KEY_RIGHT])
		{
			if(!nacis)
			{
				x++;
				if(x>wieltab[0]-1)
				x=0;
				nacis=true;
			}
		}
		else
		if(key[KEY_UP])
		{
			if(!nacis)
			{
				y--;
				if(y<0)
				y=wieltab[1]-1;
				nacis=true;
			}
		}
		else
		if(key[KEY_DOWN])
		{
			if(!nacis)
			{
				y++;
				if(y>wieltab[1]-1)
				y=0;
				nacis=true;
			}
		}
		else
		if(key[KEY_ENTER]||key[KEY_ENTER_PAD]||key[KEY_SPACE])
		{
			if(!nacis)
			{
				if(pozkal[x][y])
				{
					pozkal[x][y]=false;
					oststartpozx=startx;
					oststartpozy=starty;
					startx=x;
					starty=y;
				}
				else
				{
					if(startx==x&&starty==y)
					{
						ostcelpozx=celpozx;
						ostcelpozy=celpozy;
						celpozx=x;
						celpozy=y;
						startx=oststartpozx;
						starty=oststartpozy;
					}
					else
					{
						if(celpozx==x&&celpozy==y)
						{
							celpozx=ostcelpozx;
							celpozy=ostcelpozy;
						}
						else
						pozkal[x][y]=true;
					}
				}
				mapki.Zapis();
				nacis=true;
				clear_to_color(mapa,makecol(255,0,255));
				draw_sprite(mapa,mapa_tym,0,0);
				rysuj(0);
				draw_sprite(mapa,pionek,startx*50+50,starty*50+50);
			}
		}
		else
		if(key[KEY_G])
		{
			if(!nacis)
			{
				kier=nic;
				ruch=0;
				game(0,0,0);
				nacis=true;
			}
		}
		else
		nacis=false;
		clear_to_color(bufor,makecol(255,255,255));
		draw_sprite(bufor,mapa,0,0);
		draw_sprite(bufor,zaznaczek,x*50+50,y*50+50);
		draw_sprite(screen,bufor,0,0);
	}
	SaveMap(mapki,num);
	mapki.Zapis();
}
